#!/bin/bash

cd /cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution
tmpDir=$(mkdir -p "/cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/tmp.55454451" && echo "/cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/tmp.55454451")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution

)
out07129141="${tmpDir}/out.$$" err07129141="${tmpDir}/err.$$"
mkfifo "$out07129141" "$err07129141"
trap 'rm "$out07129141" "$err07129141"' EXIT
touch '/cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution/stdout' '/cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution/stderr'
tee '/cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution/stdout' < "$out07129141" &
tee '/cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution/stderr' < "$err07129141" >&2 &
(
cd /cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution


set -e

gatk --java-options "-Xmx8g" \
FastqToSam \
-F1 /media/spencer/lstorage/GATK/gatk-wdl/inputs/forward.fastq \
-F2 /media/spencer/lstorage/GATK/gatk-wdl/inputs/reverse.fastq \
-O RG001.unmapped.bam \
-SM S001 \
-RG RG001
)  > "$out07129141" 2> "$err07129141"
echo $? > /cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution
sync


)
mv /cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution/rc.tmp /cromwell-executions/qcFastq/07129141-9632-4453-8727-7012d706ef12/call-convertedBam_pair/execution/rc
